package model.common;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 27 15:21:40 EEST 2017
// ---------------------------------------------------------------------
public interface EmployeesViewRow extends Row {
    RowIterator getDepartmentsView();

    RowIterator getEmployeesView();

    BigDecimal getCommissionPct();

    Integer getDepartmentId();

    String getEmail();

    Integer getEmployeeId();

    String getFirstName();

    Timestamp getHireDate();

    String getJobId();

    String getLastName();

    Integer getManagerId();

    String getPhoneNumber();

    BigDecimal getSalary();

    void setCommissionPct(BigDecimal value);

    void setDepartmentId(Integer value);

    void setEmail(String value);

    void setEmployeeId(Integer value);

    void setFirstName(String value);

    void setHireDate(Timestamp value);

    void setJobId(String value);

    void setLastName(String value);

    void setManagerId(Integer value);

    void setPhoneNumber(String value);

    void setSalary(BigDecimal value);
}

